import type { Metadata, Viewport } from 'next';
import { Inter, Bebas_Neue } from 'next/font/google';
import './globals.css';
import { WhatsAppButton } from '@/components/WhatsAppButton';
import { ImageCredits } from '@/components/ImageCredits';
import VibesLayer from '@/components/VibesLayer';
import ReferralTracker from '@/components/ReferralTracker';
import { BASE_URL, SITE_NAME, SITE_DESCRIPTION } from '@/lib/siteConfig';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bebas-neue',
});

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: 'The Rasta Prophet — Blessed Love Voice of Africa',
    template: '%s — The Rasta Prophet',
  },
  description: SITE_DESCRIPTION,
  manifest: '/manifest.json',
  alternates: {
    canonical: '/',
  },
  icons: {
    icon: '/favicon.svg',
    apple: '/icons/icon-192x192.png',
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'The Rasta Prophet',
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: 'website',
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    url: BASE_URL,
    siteName: SITE_NAME,
    // Homepage OG image is generated by app/opengraph-image.tsx; Next wires it
    // into the default metadata automatically, so no explicit images array here.
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  themeColor: '#121212',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
      </head>
      <body className={`${inter.variable} ${bebasNeue.variable} bg-background text-white antialiased`}>
        {children}
        <ReferralTracker />
        <ImageCredits />
        <WhatsAppButton />
        <VibesLayer />
      </body>
    </html>
  );
}
